apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - max:
      cpu: "150m"
      memory: "150Mi"
    min:
      cpu: "50m"
      memory: "50Mi"
    default:
      cpu: "75m"
      memory: "100Mi"
    defaultRequest:
      cpu: "50m"
      memory: "50Mi"
    type: Container
    