apiVersion: v1
kind: Pod
metadata:
  name: volumes-demo-1
  labels:
    name: demo
spec:
  containers:
  - name: c1
    image: ubuntu:24.04
    command:
    - sh
    - -c
    - echo [INFO] Hello from Pod `hostname` at `date` running on $NODENAME. >> /tmp/out.txt && tail -f /tmp/out.txt
    env:
    - name: NODENAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    resources:
      limits:
        memory: "150Mi"
        cpu: "150m"
