apiVersion: v1
kind: Pod
metadata:
  name: secret-as-volume
  labels:
    name: kubectl
spec:
  volumes:
  - name: admin-conf
    secret:
      secretName: kubeconfig
  containers:
  - name: kubectl
    image: kulbhushanmayer/ubuntu:kubectl
    volumeMounts:
    - name: admin-conf
      mountPath: /mnt
    env:
    - name: KUBECONFIG
      value: /mnt/config
    command:
    - sh
    - -c
    - kubectl get pods -w
    resources:
      limits:
        memory: "150Mi"
        cpu: "150m"