apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sarah-ds-pvc
spec:
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: sarah-pvc
      containers:
      - name: ubuntu
        image: ubuntu:24.04
        command:
        - sh
        - -c
        - echo [INFO] Hello from Pod `hostname` at `date` running on $NODENAME. >> /tmp/$FILENAME.txt && tail -f /tmp/$FILENAME.txt
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: FILENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            memory: "150Mi"
            cpu: "150m"
        volumeMounts:
        - name: pvc
          mountPath: /tmp
