- name: Add Networking modules
  hosts: all
  become: yes
  tasks:
  - name: Copy to File 1
    copy:
      content: |
        overlay
        br_netfilter
      dest: /etc/modules-load.d/k8s.conf
    notify:
    - Reload System
  - name: configure modules
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
      - overlay
      - br_netfilter
  - name: Copy to File 2
    copy:
      content: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
      dest: /etc/sysctl.d/k8s.conf
    notify:
    - Reload System
  handlers:
  - name: Reload System
    shell: sysctl --system