
- name: Install Docker
  hosts: all
  become: yes
  vars: 
    PATH: "/etc/apt/keyrings"
    GPG_URL: "https://download.docker.com/linux/ubuntu/gpg"
  tasks: 
  - name: Install dependencies
    package: 
      name: "{{ item }}"  
      state: present
      update_cache: yes
    with_items:
    - ca-certificates
    - curl 
  - name: Create keyrings directory    
    file:
      path: "{{ PATH }}"
      mode: "755"
      state: directory
  - name: Get GPG keyrings
    get_url:
      url: "{{ GPG_URL }}"
      dest: "{{ PATH }}/docker.asc"
      mode: "644"
  - name: Get Arch - Setup Fact
    set_fact: 
      ARCH: amd64
      when: ansible_architecture == "x86_64"
  - name: Add Docker Repo
    apt_repository:
      repo: "deb [arch={{ ARCH }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      filename: /etc/apt/sources.list.d/docker
      state: present
      update_cache: yes
  - name: Install Docker
    package:
      name: "{{ item }}"  
      state: present
      update_cache: yes
    with_items: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
  - name: Change Owner of file
    file:
      path: /var/run/docker.sock
      owner: "{{ ansible_user_id }}"
  - name: Command to check Docker version
    shell: docker version
    register: version
    ignore_errors: yes
    tags:
    - check_status
  - name: Installation Success Status Check
    when: '"Server: Docker Engine - Community" in version.stdout'
    debug: 
      msg: "[INFO] Successfully installed Docker."
  - name: Installation Failure Status Check
    when: '"permission denied" in version.stderr'
    debug:
      msg: "[INFO] Docker Installation Failed."