- name: Install Trivy
  hosts: all
  become: yes
  vars: 
    URL: "https://aquasecurity.github.io/trivy-repo/deb/public.key"
  tasks:
  - name: Install dependencies
    package: 
      name: "{{ item }}"  
      state: present
      update_cache: yes
    with_items:
    - apt-transport-https
    - gnupg
    - lsb-release
  - name: Get GPG keyrings for Trivy
    get_url:
      url: "{{ URL}}"
      dest: /etc/apt/keyrings/trivy.esc
      mode: "644"
  - name: Add Trivy Repo
    apt_repository:
      repo: "deb [signed-by=/etc/apt/keyrings/trivy.esc] https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main"
      filename: /etc/apt/sources.list.d/trivy.list
      state: present
      update_cache: yes
  - name: Install Trivy
    package:
      name: trivy 
      state: present
      update_cache: yes

    