- name: Install Python
  hosts: all
  become: yes
  tasks:
  - name: Install dependencies
    package: 
      name: "{{ item }}"  
      state: present
      update_cache: yes
      with_items:
      - python3
      - python3-pip
      - python3-setuptools
  - name: Install requirements
    pip: 
      virtualenv: /usr/bin/env python
      virtualenv_python: python3.10.12
